<?php

/**
 * AutorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AutorTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Autor');
  }
}