<?php

/**
 * SnippetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SnippetTable extends Doctrine_Table
{
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Snippet');
  }
  
  public static function ultimos()
  {
    return self::getInstance()
      ->createQuery('s')
      ->orderby('created_at desc')
      ->execute();
  }
  
  public static function getBySlug($slug)
  {
    if (!$slug) return null;
    
    return self::getInstance()
      ->createQuery('s')
      ->where('slug = ?', $slug)
      ->fetchOne();
  }
}