<?php

/**
 * Snippet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    snippets
 * @subpackage model
 * @author     lsouza
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Snippet extends BaseSnippet
{
  public function __toString()
  {
    return (string) $this->getTitulo();
  }
}
